### ISSUE TITLE
Missing XP stats for cycle 18

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#117]
### Expected vs. Actual

there are a bunch of folks who seem to have zeros for XP last week: mike adossi, melody, john hopkins, abraham. i’m assuming this was an error in retro submissions?
 
also: mel’s stats are now in the red two weeks in a row because they didn’t receive any retro feedback (as far as i can tell) - will that be logged later?

### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._

### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
Hi, @carlabagdonas -- would you please send this request through our #support channel in echo (or assign an Asana task to "Support Engineering" directly? With our recent process changes, we're trying to use these issues as bug reports, feature requests, or suggestions for the software rather than for support / help. Thanks.

**Comment by bundacia** [comment]
This seems to have been resolved. I'm showing those players gained the following xp that cycle: <img width="358" alt="rethinkdb_administration_console" src="https://cloud.githubusercontent.com/assets/189699/21620267/836937c4-d1c1-11e6-8ba6-9ed7a9921ca1.png">
