### ISSUE TITLE
Echo sent multiple messages | Potential error calculating stats

### ISSUE THREAD

**Issue by nodatall** [LearnersGuild/los#121]
Cycle 19 -  echo sent me 3 post retro messages each with different hours for my teammate. My team was #hurried-kongoni. 

The final message was the accurate recorded hours and included the following: 
 
Your estimated contribution to the project: 44%
Expected contribution for # of hours: 41%
Contribution difference: 3%

My elo went down by 1, which seems off considering the contribution difference was 3%.

I think something wonky happened.

**Comment by jeffreywescott** [comment]
Hi, @nodatall -- we periodically re-compute stats across all projects. It's not uncommon for the results to change between computations, as data is sometimes added / adjusted. If the final message you received had the correct "raw" data, that's _good_. We send the message each time the computation runs (though in the future, we want to make stats a "pull" based process rather than a "push" based process -- we hope early in 2017).

I wouldn't overly worry about the Elo -- as long as the raw data is correct, things should be correct.
