### ISSUE TITLE
Retro from last week is not updating stats nor is it allowing me to submit

### ISSUE THREAD

**Issue by helenyau0** [LearnersGuild/los#173]
### Expected vs. Actual

_What were you attempting to do? What actually happened? Please provide your project name and/or the cycle number if applicable._

I have tried countless times submitting in my retro from last week but the data never gets saved. It shows in our project channel the retro has been 2/2 completed for #axiomatic-ringtail, however neither my partner's stats or mine got updated. If someone could look into this as soon as possible it would be greatly appreciated. 

### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._

### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by heyheyjp** [comment]
@helenyau0: can you further explain what happens when your submission fails to save? Is there an error/message? Does the form complete as normal but fail to reflect those updated values upon revisiting? Please provide as much detail as possible (screenshots are extremely helpful).

Thanks!

**Comment by helenyau0** [comment]
@prattsj I don't know if it's a bug but I can still access last week's retro even after I have submitted it. It's able to save my last inputs, but every time I submit the retro it never goes through and saves to the database. In the first screenshot you can see that the form completes as normal; I get a message "you're all done!" and I can click close to exit, but when I go to check my stats it never shows an update. Could the second screen shot be a possibility to why the retro isn't going through? After exiting the form I get this message from echo "looking for retrospective survey". It kinda seems like echo can't find the retro, and that could possibly be why our stats aren't updating...? 
![screen shot 2017-03-02 at 4 10 25 pm](https://cloud.githubusercontent.com/assets/22210582/23532857/e2f86bf0-ff62-11e6-8d09-ff5844304761.png)


![screen shot 2017-03-02 at 4 13 59 pm](https://cloud.githubusercontent.com/assets/22210582/23532939/5e90c7a8-ff63-11e6-9d2b-618334b920f4.png)

**Comment by heyheyjp** [comment]
@helenyau0: it appears that in the survey you indicated that you took off/were absent for 31 hours during the course of the project. Is that correct? It is because of this answer that the system considers you to be an inactive member of the project and therefore excludes your retro responses from consideration when updating stats. If this is incorrect (note that the wording has _changed_ from a previous version of this survey in which players are asked to enter how many hours they _DID_ work rather than the number of hours they _DID NOT_ work), please update your retro response for this question. It should trigger another stats update.

Closing this issue with the understanding (for now) that the system is behaving as intended. Please reopen if you need further assistance.
