### ISSUE TITLE
investigate possible retro bug in ahead-chuckwalla C38

### ISSUE THREAD

**Issue by needdra** [LearnersGuild/los#181]
ahead-chuckwalla
State: COMPLETE
#93 [L1]: Build Your Own Bootstrap
Apr 3 - Apr 10 [cycle 38]

i added John Ware (johnware15) to the group - team size 2 - making it a team size 3. he's been unable to submit a retro and i think it may be because of the team size. at any rate, none of the learners on the team can see their retro data and john was not able to submit his contribution - the slider wasn't there for him, but it was there for the other two people on his team. 

please let me know if there's anything i need to do to help resolve this.

**Comment by bundacia** [comment]
ok, it looks like that for that project the third player was added after the retrospective survey was created. So that player isn’t listed in the survey questions and the logic around how many people need to complete the survey got confused.

Best case scenario they’ll all have to complete the retro again. But I’ll have to do a but of fixing up the data manually first.

**Comment by bundacia** [comment]
@needdra: The survey has been fixed to include the third player. They will all three have to re-submit the retro with the new set of questions.

**Comment by bundacia** [comment]
Created a story in clubhouse to make sure the UI prevents this in the future.

https://app.clubhouse.io/learnersguild/story/2067/changing-teams-after-reflection-starts-breaks-retros
