### ISSUE TITLE
Stats Review--est. Bias/Accuracy

### ISSUE THREAD

**Issue by Briy710** [LearnersGuild/los#186]
<img width="802" alt="screen shot 2017-05-12 at 3 30 11 pm" src="https://cloud.githubusercontent.com/assets/26014707/26019706/67b70530-372c-11e7-987b-52b4eec41bc4.png">

I need some help understanding why my est. bias went down so much when I have 100% est accuracy?

**Comment by jeffreywescott** [comment]
@Briy710, I'm not sure I understand your question.

Estimation _bias_ is a positive or negative number representing how much you tend to either _overestimate_ or _underestimate_ your own contribution. So, if your estimation accuracy goes up, you should _expect_ the absolute value of your estimation bias to go _down_. More here: https://playbook.learnersguild.org/Game_Manual/Stats.html#estimation-bias

Does that help?

**Comment by heyheyjp** [comment]
@jeffreywescott: the problem here is that this change in overall estimation bias is colored red, indicating that it a _bad_ change.

**Comment by bundacia** [comment]
Ahh, that makes sense. We have logic that's indented to use the right color based whether the change got you closer or farther away from the "target" value (0 in this case), but there must be a bug.

**Comment by bundacia** [comment]
Oh, wait. This *was* a "bad" change. @Briy710's estimation bias went from positive 1.83 to negative 2.5. So in the end the change took it slightly further away from zero.

**Comment by jeffreywescott** [comment]
@bundacia: isn't POSITIVE estimation accuracy OVERestimating? In any case, I think it's neither red NOR green for bias -- bias is bias, whether you're over- or underestimating.

**Comment by heyheyjp** [comment]
There seems to be a bigger question we should be asking.

These days, everyone is either working on solo or 2-person projects. In this case, we have a 2-person team, but that seems to only make estimation accuracy _barely_ more applicable than on a 1-person team (on which it isn't applicable at all); it's just a matter of one person's opinion vs. another's, with the outcomes of only very few other "estimation matches" being also taken into account. I'm not sure people are working with enough other people to warrant _any_ measurement of estimation accuracy. At least not as currently designed.

There are similarly troubling issues with review accuracy. With the only review considered reliable coming from one person (or at most, two, with an SEP's spot check) - does the review bias of individual players even matter anymore? We're already signaling that we trust coaches to submit accurate reviews; the only comparison it seems is worth making is that of a coach's to an SEP's.

Maybe it's time for the *accuracy stats to take a backseat (be completely hidden) for a while, until we've sorted out whether or not they make sense and what the most appropriate UX design is for conveying their meaning to players.

**Comment by heyheyjp** [comment]
> Oh, wait. This was a "bad" change. @Briy710's estimation bias went from positive 1.83 to negative 2.5. So in the end the change took it slightly further away from zero.

@bundacia: ah, I see. Thanks for that clarification. It seems awkward though that what we show is the total difference. _If_ the *accuracy stats are gonna stick around (and as I've mentioned above, I'm not convinced they should), maybe we should instead be showing only the difference in, er, differences (i.e. instead of showing `↓ 4.33` for a swing from `-1.83` to `2.5`, show the change in absolute difference in red, `↑ 0.67`).

**Comment by bundacia** [comment]
@jeffreywescott: yes, I was just pointing out the the absolute value of the bias increased here. So @Briy710 went from a small overestimation bias to a slightly larger underestimation bias. In other words, their bias was farther from 0 as a result of this change, so that's why the delta is red.

@prattsj: I agree that there's probably a better way to display this data that's more about abolute value.

**Comment by heyheyjp** [comment]
No longer relevant.
