### ISSUE TITLE
echo channel 413

### ISSUE THREAD

**Issue by Maighdlyn** [LearnersGuild/los#192]
I'm in phase 2 so I did not vote for any goals this week.
Echo created channel 413 and added me to that channel this morning. I see many other members of channel 413 who I also recognize from being in phase 2, though I'm not sure if everyone in the channel is in phase 2.

**Comment by heyheyjp** [comment]
Thanks, @Maighdlyn. The issue here is that you were accidentally invited to a goal channel for an auto-managed project. Your "project" for the week is simply working on Phase 2 modules, and goal 413 is the correct "goal" for that project. But this project tracking is supposed to happen completely in the background while you're in Phase 2, so there's a bug where the system invited you to a goal channel when it shouldn't have. We'll fix it.

**Comment by heyheyjp** [comment]
Issue moved to [LearnersGuild/echo #906](https://github.com/LearnersGuild/echo/issues/906) via [**ZenHub**](https://www.zenhub.com/)
