### ISSUE TITLE
Echo Https does not work

### ISSUE THREAD

**Issue by harmanTheCarMan** [LearnersGuild/los#75]
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
I went to https://echo.learnersguild.org/ and I got the chrome error for https. 
https://aboutssl.org/wp-content/uploads/2016/03/ERR_CERT_COMMON_NAME_INVALID-chrome-error.png

I am logged into github already. 
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
Go to https://echo.learnersguild.org/ on chrome.
Be logged into github. 
Click advanced settings, choose to proceed (unsafe per chrome)
This allows you to go to echo's github login page and login to echo. 
After this, echo works but https is striked out in red.
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_
Mac os, chrome updated.

**Comment by jeffreywescott** [comment]
@harmanlearns -- our certs are fully up-to-date. This is a Chrome issue. Others have seen it as well. Make sure you're on the latest Chrome.

It's similar to this issue here, though not DigiCert: https://apple.stackexchange.com/questions/134601/chrome-showing-the-sites-security-certificate-is-not-trusted-for-github
