### ISSUE TITLE
Strongly Agree/Agree new voting mechanism/system

### ISSUE THREAD

**Issue by GeneralMeow** [LearnersGuild/los#86]
I would love to see a new method of entering the strongly disagree - strongly agree rubric. I am proposing that we change it to a 100 point sliding scale system so that we can give folks a score that is much more accurate and gives us more control over exact numbers. The distance between agree and strongly agree is enough that I would love to have the option to choose, since the distance is full of so much nuance. 
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by Moniarchy** [comment]
I would like to see a sliding scale too.

**Comment by lizzkats** [comment]
This. Please!

**Comment by jeffreywescott** [comment]
Thanks for the suggestion, @GeneralMeow (and @Moniarchy / @lizzkats). We totally understand the sentiment around this request, but strongly disagree with it. Here's why:

[Likert scales](https://en.wikipedia.org/wiki/Likert_scale) are _designed_ to normalize psychometric data on questionnaires over a group of people, so while it runs the risk of being _less accurate_ for an individual answering a question, it ends up giving a _more truthful **average**_ answer for a question answered by a _group_ of people (which as you can imagine when computing stats, is more important than any individual response). There's a ton of mathematical research into modeling this stuff in order to provide "reliable" survey data.

Cheers.
