### ISSUE TITLE
Echo feedback

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#9]
I'd like to be able to:
- vote with a comma, slash, or ampersand between numbers (6, 3) (6/3) or (6&3)
- vote for my two goals with two separate messages (i.e. /vote 6 (send) then /vote 3) instead of having to re-type them both in the same message

Voting:
- it wasn't clear to me whether i could use both votes for the same goal. when i tried to do it, i couldn't tell whether both votes had actually counted towards the same goal (I just saw my "1st" choice + photo, didn't see anything for my 2nd choice). I thought it had only counted one of my votes.
- wasn't clear to me when a voting cycle had started (no message in my echo feed)

Editing messages in Echo:
- the "edit message" UI wasn't intuitive to me since i was used to Slack's setup - I was expecting to click the "edit" button near the message and then be able to edit text in-line instead of having to edit down at the bottom of the screen in my normal message box. it wasn't clear whether i was typing a new message or editing an existing one (although the yellow background coloring helped)

Teams / Projects / Goals:
- team list should show all members, even if they're not online (maybe in grey or italics) - confusing to have to click "show all members" in order to see everyone
- The distinction between team, project, and goal isn't clear to me. It feels like the "project" is the goal we're working towards. The adjective-animal feels like the team name because it's the label that unifies us as a group of people working towards the same goal / working on the same project.

Reviewing:
- I'd like to be able to see the review scores I gave, after I submit them
- Can I change them later? 
- Good that scores can be submitted with or without a space between the letter and number (e.g. c 89 or c89)
- Why the double-dash for full words (--completeness) and single-dash for the single letter (-c)? Seems like more room for confusion / error
- Where do I find my team list when I go to give relative contribution scores?
- When I list my teammates names, do I write their handle or first name? The example shows first names, which makes me think that's what I'm supposed to do, but the question list gives handles. 
- If I enter people's names in the wrong format (e.g. I entered them as @prattsj instead of just "prattsj" and then it told me that those people were not on my team). If that happens, it should remind me of the scores I entered so I can just easily re-write them (and not have to remember or re-calculate). Even better, it should recognize them with or without the @ in front of the name.

Nice to have:
- There should be a relative contribution calculator on-hand 
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
> I'd like to be able to:
> 
> vote with a comma, slash, or ampersand between numbers (6, 3) (6/3) or (6&3)

We probably won't go this route because we're trying to maintain a more or less "standard" command-line interface that programmers will encounter in their day-to-day life.

> vote for my two goals with two separate messages (i.e. /vote 6 (send) then /vote 3) instead of having to re-type them both in the same message

The reason we didn't go this route was because we wanted a quick and easy way for players to express _which_ goal they prefer. So the left-most goal ID is the first choice. We may revisit this once we allow for more than 2 goals to be voted on at a time.

> Voting:
> 
> it wasn't clear to me whether i could use both votes for the same goal. when i tried to do it, i couldn't tell whether both votes had actually counted towards the same goal (I just saw my "1st" choice + photo, didn't see anything for my 2nd choice). I thought it had only counted one of my votes.

Great feedback -- we are going to disallow multiple votes for the same goal.

> wasn't clear to me when a voting cycle had started (no message in my echo feed)

We will be improving the messages that players receive. Thank you.

> Editing messages in Echo:
> 
> the "edit message" UI wasn't intuitive to me since i was used to Slack's setup - I was expecting to click the "edit" button near the message and then be able to edit text in-line instead of having to edit down at the bottom of the screen in my normal message box. it wasn't clear whether i was typing a new message or editing an existing one (although the yellow background coloring helped)

We may address this at a later time, but don't have plans to right now. 

> Teams / Projects / Goals:
> 
> team list should show all members, even if they're not online (maybe in grey or italics) - confusing to have to click "show all members" in order to see everyone

We will investigate to see if we can make this better.

> The distinction between team, project, and goal isn't clear to me. It feels like the "project" is the goal we're working towards. The adjective-animal feels like the team name because it's the label that unifies us as a group of people working towards the same goal / working on the same project.

Yes -- it's a bit confusing because, long-term, projects may span multiple cycles, and the team composition for that project may change from cycle-to-cycle. But this is good feedback. We need to make sure players are clear on the difference. There's actually not really a "Team" object _at all_ in the system. Just projects and goals.

> Reviewing:
> 
> I'd like to be able to see the review scores I gave, after I submit them

We'll be adding a way to see what you've already reviewed and what scores you gave.

> Can I change them later?

Yes. :-)

> Good that scores can be submitted with or without a space between the letter and number (e.g. c 89 or c89)
> Why the double-dash for full words (--completeness) and single-dash for the single letter (-c)? Seems like more room for confusion / error

This is the standard way that these types of command-line interfaces are done. It has to do with your previous comment, since we could have an option called `--c89` and it would be difficult to determine whether the second character after the option is the value for that option or the next letter of the option name. Again, programmers need to get used to this, so we won't be changing it.

> Where do I find my team list when I go to give relative contribution scores?

We will be broadcasting it to all players once projects are formed. Great feedback, thanks!

> When I list my teammates names, do I write their handle or first name? The example shows first names, which makes me think that's what I'm supposed to do, but the question list gives handles.

We should improve the examples. It's in our backlog.

> If I enter people's names in the wrong format (e.g. I entered them as @prattsj instead of just "prattsj" and then it told me that those people were not on my team). If that happens, it should remind me of the scores I entered so I can just easily re-write them (and not have to remember or re-calculate). Even better, it should recognize them with or without the @ in front of the name.

All commands will now be echoed back to the user (privately) after they're typed-in. Great feedback. Thanks.

> Nice to have:
> 
> There should be a relative contribution calculator on-hand

We are actually looking at a completely revamped user interface for the retrospectives. Stay tuned.
